name = "TwizzyCraft 3.5"
author = "mossad"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "087d8773f84843f7ae2547165a7f1d213d7e6438af6dcb9f11769fa346a32e02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
