name = "TwizzyCraft 3.5"
author = "mossad"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab18487b0e58c5bc31ad65d309a4f120494a6e7309ebffcfa20d79b5b59f6cce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
