name = "TwizzyCraft 3.5"
author = "mossad"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c2c32876655bd7f7ca6ebd2f38fb89110ce2e5509716d4782457163779eabfa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
