// Adds Budding Geore recipes to Oritech Foundry

<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_coal", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:coal_block"}, {item: "minecraft:coal_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_coal"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_copper", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:copper_block"}, {item: "minecraft:copper_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_copper"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_diamond", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:diamond_block"}, {item: "minecraft:diamond_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_diamond"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_emerald", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:emerald_block"}, {item: "minecraft:emerald_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_emerald"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_gold", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:gold_block"}, {item: "minecraft:gold_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_gold"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_iron", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:iron_block"}, {item: "minecraft:iron_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_iron"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_lapis", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:lapis_block"}, {item: "minecraft:lapis_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_lapis"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_quartz", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:quartz_block"}, {item: "minecraft:quartz_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_quartz"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_redstone", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "minecraft:redstone_block"}, {item: "minecraft:redstone_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_redstone"}]});

//Adds Modded Budding Geore recipes to Oritech Foundry
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_zinc", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "create:zinc_block"}, {item: "create:zinc_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_zinc"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_uranium", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "oritech:uranium_dust_block"}, {item: "oritech:uranium_dust_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_uranium"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_platinum", {ingredients: [{item: "minecraft:budding_amethyst"}, {tag: "c:storage_blocks/platinum"}, {tag: "c:storage_blocks/platinum"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_platinum"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_lead", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "tfmg:lead_block"}, {item: "tfmg:lead_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_lead"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_aluminum", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "tfmg:aluminum_block"}, {item: "tfmg:aluminum_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_aluminum"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_nickel", {ingredients: [{item: "minecraft:budding_amethyst"}, {tag: "c:storage_blocks/nickel"}, {tag: "c:storage_blocks/nickel"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_nickel"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_ruby", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "irons_jewelry:ruby_block"}, {item: "irons_jewelry:ruby_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_ruby"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_topaz", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "irons_jewelry:topaz_block"}, {item: "irons_jewelry:topaz_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_topaz"}]});
<recipetype:oritech:assembler>.addJsonRecipe("oritech:assembler/budding_sapphire", {ingredients: [{item: "minecraft:budding_amethyst"}, {item: "irons_jewelry:sapphire_block"}, {item: "irons_jewelry:sapphire_block"}, {item: "oritech:enderic_compound"}], time: 96, type: "oritech:assembler", results: [{count: 1, id: "geore:budding_sapphire"}]});